import easygui as gui
# gui.msgbox("hello world", "aplication", image = "topic_11/python.png")
# gui.ccbox("play agein", "aplication", choices= ("yes", "no"))
# out = gui.ccbox("play agein", "aplication", choices= ("yes", "no"))
# gui.msgbox(out, "aplication", image = "topic_11/python.png")
# out = gui.boolbox("play agein", "aplication")
# gui.msgbox(out, "aplication", image = "topic_11/python.png")
# out = gui.buttonbox("play agein", "aplication", choices= [str(i) for i in range(1,20)],images = ["topic_11/python.png"] * 3)
# gui.msgbox(out, "aplication", image = "topic_11/python.png")
# out = gui.indexbox("play agein", "aplication", choices= ["788"+str(i) for i in range(1,20)], image = "topic_11/python.png")
# gui.msgbox(out, "aplication", image = "topic_11/python.png")
# gui.enterbox()
# gui.integerbox()
# gui.multenterbox()
# gui.pusswordbox()
# gui.multpusswordbox()
# gui.textbox()
# gui.codebox()
